name: Install, build, and test

on: [push, pull_request]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [12.x]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1

    - name: Install Cypress dependencies (xvfb, libgtk-3-dev, libnotify-dev, libgconf-2-4, libnss3, libxss1, libasound2)
      run: sudo apt-get install xvfb libgtk-3-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: yarn install
      uses: borales/actions-yarn@v2.1.0
      with:
        cmd: install

    - name: yarn build
      uses: borales/actions-yarn@v2.1.0
      with:
        cmd: build

    - name: yarn test
      uses: borales/actions-yarn@v2.1.0
      with:
        cmd: test
      env:
        CI: true
