name: Install, build, and test

on: [push, pull_request]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [10.x]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install

    - name: yarn install, build, and test
      run: |
        yarn install
        yarn build --if-present
        yarn test
      env:
        CI: true
